server.port=8081

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/poc
spring.datasource.username=postgres
spring.datasource.password=marco
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Ollama (para generar el embedding de la consulta del usuario) ---
ollama.base-url=http://localhost:11434
# Debe ser EL MISMO modelo que usaste para generar vector_embedding al indexar los PDFs,
# de lo contrario los vectores no son comparables entre sí.
### ollama.embedding-model=all-minilm
##ollama.embedding-model=llama3.2:3b
ollama.embedding-model=nomic-embed-text

# Idioma para tsvector / tsquery (debe coincidir con el usado al crear texto_busqueda)
busqueda.idioma-postgres=spanish

# Swagger UI queda disponible en: http://localhost:8081/swagger-ui.html
# El JSON de OpenAPI queda en:     http://localhost:8081/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true